version: "3.9"

services:
  server:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
